### PR TITLE
Use device path for --attach-as argument

### PR DESCRIPTION
**Pull request by fstehle**
in order to have consistent EBS volume names in AWS.

cc: @Jimdo/platform 

TODO:
- [ ] Update userdata

### CODE REVIEW

**Comment by bracki** [comment]
LGTM

**Comment by s0enke** [comment]
🎉

**Comment by skrings** [comment]
❤️

**Comment by fungusakafungus** [comment]
old pull requests be like alumni meetings

**Comment by schnipseljagd** [comment]
Ciao!

**Comment by Bonko** [comment]
Did anyone say beer?

**Comment by bracki** [comment]
push oder pull deployment?

**Comment by p0wl** [comment]
close & rewrite in rust?

**Pull request closed without merging**
